const translations = {
  fr: {
    navAbout: "À propos",
    navFeatures: "Fonctionnalités",
    navInterface: "Interface",
    navContact: "Contact",
    heroBadge: "Comptivo V1.03 • Solution professionnelle • Windows 10/11",
    heroTitle: "Valorisez votre analyse comptable avec une solution plus claire, plus rapide et plus professionnelle.",
    heroText: "Comptivo est une solution moderne d'analyse et de contrôle comptable conçue pour aider les professionnels à mieux lire leurs données, structurer leurs vérifications et gagner un temps précieux au quotidien.",
    heroPrimary: "Découvrir Comptivo",
    heroSecondary: "Demander une présentation",
    point1Title: "Analyse comptable avancée",
    point1Text: "Recherche, contrôle et lecture intelligente des données",
    point2Title: "Tableaux de bord & indicateurs",
    point2Text: "Une vision claire pour piloter l'activité",
    point3Title: "Usage professionnel sécurisé",
    point3Text: "Données conservées sur votre poste de travail",
    demoLabel: "Aperçu de l'interface — illustration promotionnelle avec données fictives",
    strip1: "Recherche globale",
    strip2: "Tableaux de bord",
    strip3: "Fichiers fiscaux",
    strip4: "Soldes antérieurs",
    strip5: "Détection des anomalies",
    aboutKicker: "À propos",
    aboutTitle: "Comptivo, une solution pensée pour moderniser l'analyse comptable.",
    aboutP1: "Comptivo est un logiciel professionnel dédié à l'analyse et au contrôle comptable. Il permet d'accéder plus rapidement à l'information, de visualiser des indicateurs pertinents et de centraliser les opérations de vérification dans un seul environnement de travail.",
    aboutP2: "Pensé pour les professionnels, Comptivo accompagne l'utilisateur dans ses contrôles sans jamais remplacer son jugement métier. Les alertes sont présentées comme des points à vérifier afin d'encourager une lecture rigoureuse et responsable.",
    featuresKicker: "Fonctionnalités",
    featuresTitle: "Des fonctionnalités utiles, concrètes et orientées performance.",
    featuresIntro: "Comptivo réunit les outils essentiels pour simplifier les lectures, accélérer les recherches et professionnaliser le contrôle comptable.",
    f1Title: "Recherche globale",
    f1Text: "Retrouvez immédiatement un compte, un tier, une pièce, une référence, un journal, un libellé ou un montant.",
    f2Title: "Tableau de bord décisionnel",
    f2Text: "Accédez en un coup d'œil aux indicateurs clés, aux chiffres synthétiques et aux informations importantes.",
    f3Title: "Fichiers fiscaux",
    f3Text: "Travaillez efficacement avec les modèles TVA, TAP, TVA à déduire et IRG directement depuis le logiciel.",
    f4Title: "Soldes antérieurs",
    f4Text: "Importez et exploitez les soldes antérieurs avec une logique adaptée aux comptes et aux tiers.",
    f5Title: "Anomalies potentielles",
    f5Text: "Identifiez rapidement les opérations qui nécessitent une vérification, sans conclure automatiquement à une erreur.",
    f6Title: "Mise à jour intégrée",
    f6Text: "Faites évoluer l'application simplement grâce à un système de mise à jour manuelle intégré.",
    interfaceKicker: "Interface",
    interfaceTitle: "Une interface moderne qui met l'information utile au premier plan.",
    interfaceText1: "Comptivo a été conçu pour offrir une lecture fluide, structurée et professionnelle des données comptables. Les indicateurs, états et informations importantes sont visibles rapidement.",
    interfaceText2: "L'aperçu présenté ici constitue une illustration promotionnelle basée sur une capture du logiciel, avec des données entièrement fictives.",
    b1: "Navigation claire, simple et professionnelle.",
    b2: "Lecture rapide des indicateurs les plus importants.",
    b3: "Vision synthétique pour mieux orienter vos vérifications.",
    b4: "Présentation soignée adaptée à un usage métier.",
    audienceKicker: "Pour qui ?",
    audienceTitle: "Une solution conçue pour les professionnels de la comptabilité et de la gestion.",
    a1Title: "Comptables",
    a1Text: "Pour accélérer les contrôles, gagner du temps et exploiter plus efficacement l'information comptable.",
    a2Title: "Cabinets comptables",
    a2Text: "Pour centraliser l'analyse, améliorer le suivi des dossiers et renforcer la qualité du contrôle.",
    a3Title: "Entreprises",
    a3Text: "Pour obtenir une lecture plus claire de la comptabilité et identifier plus vite les points à vérifier.",
    ctaKicker: "Pourquoi choisir Comptivo ?",
    ctaTitle: "Un outil pensé pour allier clarté, efficacité et rigueur professionnelle.",
    ctaText: "Comptivo vous aide à structurer vos analyses, à gagner du temps dans vos recherches et à professionnaliser vos vérifications comptables dans un environnement moderne et pratique.",
    ctaButton: "Demander des informations",
    contactKicker: "Contact",
    contactTitle: "Faites découvrir Comptivo à votre structure.",
    contactIntro: "Pour demander une présentation, obtenir plus d'informations, discuter d'un besoin ou connaître les modalités d'accès au logiciel, contactez-nous directement.",
    contactNotice: "Le logiciel n’est pas disponible en téléchargement direct sur le site. L’accès est proposé après prise de contact.",
    contactEmailTitle: "E-mail",
    contactFacebookTitle: "Facebook",
    contactFacebookText: "Page officielle Comptivo",
    panelTitle: "Comptivo",
    panelText: "Une solution professionnelle d'analyse et de contrôle comptable conçue pour offrir une lecture plus claire, plus rapide et plus efficace de vos données.",
    panelNote: "Téléchargement non public — accès et mise à disposition après contact.",
    panelEmailButton: "Nous écrire",
    panelFacebookButton: "Visiter la page Facebook",
    footerText: "Comptivo — site promotionnel multilingue."
  },
  en: {
    navAbout: "About",
    navFeatures: "Features",
    navInterface: "Interface",
    navContact: "Contact",
    heroBadge: "Comptivo V1.03 • Professional Solution • Windows 10/11",
    heroTitle: "Elevate your accounting analysis with a solution that is clearer, faster, and more professional.",
    heroText: "Comptivo is a modern accounting analysis and control solution designed to help professionals read their data more clearly, organize their reviews, and save valuable time every day.",
    heroPrimary: "Discover Comptivo",
    heroSecondary: "Request a presentation",
    point1Title: "Advanced accounting analysis",
    point1Text: "Smart search, control, and data review",
    point2Title: "Dashboards & indicators",
    point2Text: "A clear view to better monitor activity",
    point3Title: "Professional and secure use",
    point3Text: "Data remains stored on your workstation",
    demoLabel: "Interface preview — promotional illustration with fictional data",
    strip1: "Global search",
    strip2: "Dashboards",
    strip3: "Tax files",
    strip4: "Opening balances",
    strip5: "Anomaly detection",
    aboutKicker: "About",
    aboutTitle: "Comptivo, a solution designed to modernize accounting analysis.",
    aboutP1: "Comptivo is professional software dedicated to accounting analysis and control. It helps users access information faster, visualize meaningful indicators, and centralize review operations within a single workspace.",
    aboutP2: "Designed for professionals, Comptivo supports the user’s review process without replacing professional judgment. Alerts are presented as items to verify, encouraging a rigorous and responsible approach.",
    featuresKicker: "Features",
    featuresTitle: "Useful, practical, and performance-oriented features.",
    featuresIntro: "Comptivo brings together essential tools to simplify data reading, speed up searches, and professionalize accounting control.",
    f1Title: "Global search",
    f1Text: "Instantly find an account, third party, document number, reference, journal, description, or amount.",
    f2Title: "Decision dashboard",
    f2Text: "Access key indicators, summary figures, and important information at a glance.",
    f3Title: "Tax files",
    f3Text: "Work efficiently with VAT, TAP, deductible VAT, and IRG templates directly from the software.",
    f4Title: "Opening balances",
    f4Text: "Import and use opening balances with logic adapted to accounts and third parties.",
    f5Title: "Potential anomalies",
    f5Text: "Quickly identify transactions that require review without automatically labeling them as errors.",
    f6Title: "Built-in updates",
    f6Text: "Keep the application evolving easily through an integrated manual update system.",
    interfaceKicker: "Interface",
    interfaceTitle: "A modern interface that puts useful information first.",
    interfaceText1: "Comptivo was designed to provide a smooth, structured, and professional reading experience for accounting data. Indicators, reports, and important information are visible quickly.",
    interfaceText2: "The preview shown here is a promotional illustration based on a software screenshot using entirely fictional data.",
    b1: "Clear, simple, and professional navigation.",
    b2: "Fast reading of the most important indicators.",
    b3: "A concise view to better guide your reviews.",
    b4: "A polished presentation suitable for professional use.",
    audienceKicker: "Who is it for?",
    audienceTitle: "A solution designed for accounting and management professionals.",
    a1Title: "Accountants",
    a1Text: "To speed up reviews, save time, and make better use of accounting information.",
    a2Title: "Accounting firms",
    a2Text: "To centralize analysis, improve file follow-up, and strengthen control quality.",
    a3Title: "Companies",
    a3Text: "To gain a clearer understanding of accounting and quickly identify items that need review.",
    ctaKicker: "Why choose Comptivo?",
    ctaTitle: "A tool designed to combine clarity, efficiency, and professional rigor.",
    ctaText: "Comptivo helps you structure your analysis, save time in your searches, and professionalize your accounting reviews in a modern and practical environment.",
    ctaButton: "Request information",
    contactKicker: "Contact",
    contactTitle: "Introduce Comptivo to your organization.",
    contactIntro: "To request a presentation, get more information, discuss your needs, or learn about access conditions to the software, contact us directly.",
    contactNotice: "The software is not available for direct download on the website. Access is provided after contact.",
    contactEmailTitle: "Email",
    contactFacebookTitle: "Facebook",
    contactFacebookText: "Official Comptivo page",
    panelTitle: "Comptivo",
    panelText: "A professional accounting analysis and control solution designed to deliver a clearer, faster, and more efficient reading of your data.",
    panelNote: "No public download — access is provided after contact.",
    panelEmailButton: "Write to us",
    panelFacebookButton: "Visit Facebook page",
    footerText: "Comptivo — multilingual promotional website."
  },
  ar: {
    navAbout: "حول البرنامج",
    navFeatures: "المزايا",
    navInterface: "الواجهة",
    navContact: "التواصل",
    heroBadge: "Comptivo V1.03 • حل احترافي • ويندوز 10/11",
    heroTitle: "طوّر تحليلك المحاسبي مع حل أوضح وأسرع وأكثر احترافية.",
    heroText: "Comptivo هو حل حديث للتحليل والمراقبة المحاسبية، صُمم لمساعدة المهنيين على قراءة بياناتهم بشكل أوضح، وتنظيم عمليات المراجعة، وربح وقت ثمين في العمل اليومي.",
    heroPrimary: "اكتشف Comptivo",
    heroSecondary: "اطلب عرضًا تقديميًا",
    point1Title: "تحليل محاسبي متقدم",
    point1Text: "بحث ذكي ومراقبة وقراءة أفضل للبيانات",
    point2Title: "لوحات قيادة ومؤشرات",
    point2Text: "رؤية واضحة لمتابعة النشاط بشكل أفضل",
    point3Title: "استخدام مهني وآمن",
    point3Text: "البيانات محفوظة على جهاز العمل الخاص بك",
    demoLabel: "معاينة للواجهة — عرض ترويجي ببيانات وهمية",
    strip1: "بحث شامل",
    strip2: "لوحات قيادة",
    strip3: "ملفات جبائية",
    strip4: "الأرصدة السابقة",
    strip5: "كشف الشذوذ",
    aboutKicker: "حول البرنامج",
    aboutTitle: "Comptivo، حل صُمم لتحديث التحليل المحاسبي.",
    aboutP1: "Comptivo هو برنامج احترافي مخصص للتحليل والمراقبة المحاسبية. يساعد المستخدم على الوصول إلى المعلومات بسرعة أكبر، وعرض مؤشرات مفيدة، وتجميع عمليات التحقق داخل بيئة عمل واحدة.",
    aboutP2: "صُمم Comptivo للمهنيين، وهو يرافق المستخدم في المراجعة دون أن يعوّض الحكم المهني. تُعرض التنبيهات كنقاط يجب التحقق منها من أجل قراءة دقيقة ومسؤولة.",
    featuresKicker: "المزايا",
    featuresTitle: "مزايا عملية وفعالة موجهة للأداء المهني.",
    featuresIntro: "يجمع Comptivo الأدوات الأساسية التي تبسط قراءة البيانات، وتسرّع البحث، وترفع من احترافية المراقبة المحاسبية.",
    f1Title: "بحث شامل",
    f1Text: "اعثر فورًا على حساب أو طرف أو رقم وثيقة أو مرجع أو يومية أو بيان أو مبلغ.",
    f2Title: "لوحة قيادة تحليلية",
    f2Text: "اطّلع بسرعة على المؤشرات الأساسية والأرقام الملخصة والمعلومات المهمة.",
    f3Title: "ملفات جبائية",
    f3Text: "اعمل بكفاءة على نماذج TVA وTAP وTVA à déduire وIRG مباشرة من البرنامج.",
    f4Title: "الأرصدة السابقة",
    f4Text: "استيراد واستغلال الأرصدة السابقة بمنهجية مناسبة للحسابات والأطراف.",
    f5Title: "شذوذات محتملة",
    f5Text: "اكتشف بسرعة العمليات التي تحتاج إلى تحقق دون اعتبارها أخطاء بشكل آلي.",
    f6Title: "تحديث مدمج",
    f6Text: "طوّر التطبيق بسهولة عبر نظام تحديث يدوي مدمج.",
    interfaceKicker: "الواجهة",
    interfaceTitle: "واجهة حديثة تضع المعلومات المهمة في الواجهة.",
    interfaceText1: "صُممت واجهة Comptivo لتمنح قراءة سلسة ومنظمة واحترافية للبيانات المحاسبية، حيث تظهر المؤشرات والتقارير والمعلومات المهمة بسرعة.",
    interfaceText2: "المعاينة المعروضة هنا عبارة عن عرض ترويجي مبني على لقطة من البرنامج مع بيانات وهمية بالكامل.",
    b1: "تنقل واضح وبسيط واحترافي.",
    b2: "قراءة سريعة لأهم المؤشرات.",
    b3: "رؤية مختصرة تساعد على توجيه المراجعة بشكل أفضل.",
    b4: "عرض أنيق ومناسب للاستعمال المهني.",
    audienceKicker: "لمن هذا البرنامج؟",
    audienceTitle: "حل موجه لمهنيي المحاسبة والتسيير.",
    a1Title: "المحاسبون",
    a1Text: "لتسريع عمليات المراجعة، وربح الوقت، واستغلال المعلومات المحاسبية بشكل أفضل.",
    a2Title: "مكاتب المحاسبة",
    a2Text: "لتجميع التحليل، وتحسين متابعة الملفات، وتعزيز جودة المراقبة.",
    a3Title: "الشركات",
    a3Text: "للحصول على رؤية أوضح للمحاسبة واكتشاف النقاط التي تحتاج إلى تحقق بسرعة.",
    ctaKicker: "لماذا تختار Comptivo؟",
    ctaTitle: "أداة صُممت لتجمع بين الوضوح والكفاءة والانضباط المهني.",
    ctaText: "يساعدك Comptivo على تنظيم التحليل، وربح الوقت في البحث، ورفع مستوى المراجعة المحاسبية داخل بيئة حديثة وعملية.",
    ctaButton: "اطلب معلومات",
    contactKicker: "التواصل",
    contactTitle: "عرّف مؤسستك على Comptivo.",
    contactIntro: "لطلب عرض تقديمي، أو الحصول على معلومات إضافية، أو مناقشة احتياجك، أو معرفة كيفية الوصول إلى البرنامج، تواصل معنا مباشرة.",
    contactNotice: "البرنامج غير متاح للتحميل المباشر من الموقع، ويتم توفيره بعد التواصل.",
    contactEmailTitle: "البريد الإلكتروني",
    contactFacebookTitle: "فيسبوك",
    contactFacebookText: "الصفحة الرسمية لـ Comptivo",
    panelTitle: "Comptivo",
    panelText: "حل احترافي للتحليل والمراقبة المحاسبية صُمم ليمنحك قراءة أوضح وأسرع وأكثر فعالية لبياناتك.",
    panelNote: "لا يوجد تحميل عمومي — يتم توفير الوصول إلى البرنامج بعد التواصل.",
    panelEmailButton: "راسلنا",
    panelFacebookButton: "زيارة صفحة فيسبوك",
    footerText: "Comptivo — موقع ترويجي متعدد اللغات."
  }
};

function setLanguage(lang){
  const dict = translations[lang] || translations.fr;
  document.documentElement.lang = lang === 'ar' ? 'ar' : lang;
  document.body.dir = lang === 'ar' ? 'rtl' : 'ltr';

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if(dict[key]) el.textContent = dict[key];
  });

  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  localStorage.setItem('comptivo_lang', lang);
}

const savedLang = localStorage.getItem('comptivo_lang') || 'fr';
setLanguage(savedLang);

document.querySelectorAll('.lang-btn').forEach(btn => {
  btn.addEventListener('click', () => setLanguage(btn.dataset.lang));
});

const menuToggle = document.getElementById('menuToggle');
const mainNav = document.getElementById('mainNav');
menuToggle?.addEventListener('click', () => {
  mainNav.classList.toggle('open');
});

document.querySelectorAll('.main-nav a').forEach(link => {
  link.addEventListener('click', () => mainNav.classList.remove('open'));
});
