
const translations = {
  fr: {
    navAbout: "À propos",
    navFeatures: "Fonctionnalités",
    navInterface: "Interface",
    navContact: "Contact",
    heroBadge: "Comptivo V1.03 • Windows 10/11",
    heroTitle: "L'analyse comptable plus claire, plus rapide, plus structurée.",
    heroText: "Comptivo centralise vos contrôles, vos recherches et vos états comptables dans une interface moderne conçue pour gagner du temps et mieux exploiter vos données.",
    heroPrimary: "Découvrir le logiciel",
    heroSecondary: "Nous contacter",
    point1Title: "Analyse comptable",
    point1Text: "Recherche, contrôle et lecture des données",
    point2Title: "États & indicateurs",
    point2Text: "Vision centralisée de l'activité",
    point3Title: "Données locales",
    point3Text: "Conservation sur votre poste de travail",
    demoLabel: "Aperçu de l'interface — données fictives",
    strip1: "Recherche globale",
    strip2: "États comptables",
    strip3: "Fichiers fiscaux",
    strip4: "Soldes antérieurs",
    strip5: "Détection des anomalies",
    aboutKicker: "À propos",
    aboutTitle: "Une solution pensée pour simplifier l'analyse comptable.",
    aboutP1: "Comptivo est un logiciel dédié à l'analyse et au contrôle comptable. Il aide les professionnels à retrouver plus vite l'information, à visualiser des indicateurs utiles et à organiser leurs vérifications dans un seul environnement.",
    aboutP2: "Le logiciel accompagne l'utilisateur dans ses contrôles sans remplacer son jugement professionnel. Les alertes doivent être comprises comme des points à vérifier, et non comme des erreurs déclarées automatiquement.",
    featuresKicker: "Fonctionnalités",
    featuresTitle: "Les outils essentiels réunis dans une seule application.",
    featuresIntro: "Comptivo offre une interface claire pour travailler plus efficacement sur vos données comptables.",
    f1Title: "Recherche globale",
    f1Text: "Retrouvez rapidement un compte, un tier, une pièce, une référence, un journal, un libellé ou un montant.",
    f2Title: "Tableau de bord",
    f2Text: "Suivez les indicateurs clés, les chiffres synthétiques et les informations utiles dans une vue d'ensemble moderne.",
    f3Title: "Fichiers fiscaux",
    f3Text: "Travaillez avec les modèles TVA, TAP, TVA à déduire et IRG depuis le programme.",
    f4Title: "Soldes antérieurs",
    f4Text: "Importez et exploitez les soldes antérieurs avec une gestion adaptée aux comptes et aux tiers.",
    f5Title: "Anomalies potentielles",
    f5Text: "Repérez les opérations qui nécessitent une vérification sans conclure automatiquement à une erreur.",
    f6Title: "Mise à jour intégrée",
    f6Text: "Faites évoluer l'application grâce à un système de mise à jour manuelle intégré.",
    interfaceKicker: "Interface",
    interfaceTitle: "Une interface claire pour mieux lire vos données.",
    interfaceText1: "L'interface de Comptivo met en avant l'essentiel : les indicateurs, les états, les recherches et les éléments qui méritent votre attention.",
    interfaceText2: "L'aperçu affiché ici est une illustration promotionnelle basée sur une capture du logiciel avec des données fictives.",
    b1: "Navigation simple et organisée.",
    b2: "Lecture rapide des indicateurs importants.",
    b3: "Vision synthétique des informations clés.",
    b4: "Présentation adaptée à un usage professionnel.",
    audienceKicker: "Pour qui ?",
    audienceTitle: "Une solution destinée aux professionnels et structures comptables.",
    a1Title: "Comptables",
    a1Text: "Pour accélérer les contrôles et retrouver rapidement l'information utile.",
    a2Title: "Cabinets comptables",
    a2Text: "Pour centraliser l'analyse et améliorer le suivi des dossiers.",
    a3Title: "Entreprises",
    a3Text: "Pour disposer d'une lecture plus claire de la comptabilité et des points à vérifier.",
    ctaKicker: "Pourquoi Comptivo ?",
    ctaTitle: "Plus simple. Plus rapide. Plus structuré.",
    ctaText: "Comptivo vous aide à gagner du temps dans vos lectures, recherches et vérifications comptables tout en gardant l'utilisateur au centre de la décision.",
    ctaButton: "Demander des informations",
    contactKicker: "Contact",
    contactTitle: "Parlons de votre besoin avec Comptivo.",
    contactIntro: "Pour une présentation du logiciel, une demande d'information ou un échange professionnel, vous pouvez nous contacter via les moyens ci-dessous.",
    contactEmailTitle: "E-mail",
    contactFacebookTitle: "Facebook",
    contactFacebookText: "Page officielle Comptivo",
    panelTitle: "Comptivo",
    panelText: "Logiciel d'analyse et de contrôle comptable conçu pour offrir une lecture plus claire et plus efficace de vos données.",
    panelEmailButton: "Envoyer un e-mail",
    panelFacebookButton: "Visiter Facebook",
    footerText: "Comptivo — présentation promotionnelle multilingue."
  },
  en: {
    navAbout: "About",
    navFeatures: "Features",
    navInterface: "Interface",
    navContact: "Contact",
    heroBadge: "Comptivo V1.03 • Windows 10/11",
    heroTitle: "Accounting analysis made clearer, faster, and more structured.",
    heroText: "Comptivo centralizes your controls, searches, and accounting views in a modern interface designed to save time and help you use your data more efficiently.",
    heroPrimary: "Discover the software",
    heroSecondary: "Contact us",
    point1Title: "Accounting analysis",
    point1Text: "Search, control, and data review",
    point2Title: "Reports & indicators",
    point2Text: "A centralized view of activity",
    point3Title: "Local data",
    point3Text: "Stored on your workstation",
    demoLabel: "Interface preview — fictional data",
    strip1: "Global search",
    strip2: "Accounting reports",
    strip3: "Tax files",
    strip4: "Opening balances",
    strip5: "Anomaly detection",
    aboutKicker: "About",
    aboutTitle: "A solution designed to simplify accounting analysis.",
    aboutP1: "Comptivo is software dedicated to accounting analysis and control. It helps professionals find information faster, visualize useful indicators, and organize their checks in a single environment.",
    aboutP2: "The software supports users in their reviews without replacing professional judgment. Alerts should be understood as items to verify, not automatically declared errors.",
    featuresKicker: "Features",
    featuresTitle: "Essential tools gathered in a single application.",
    featuresIntro: "Comptivo offers a clear interface to work more efficiently with your accounting data.",
    f1Title: "Global search",
    f1Text: "Quickly find an account, third party, document number, reference, journal entry, description, or amount.",
    f2Title: "Dashboard",
    f2Text: "Monitor key indicators, summary figures, and useful information in a modern overview.",
    f3Title: "Tax files",
    f3Text: "Work with VAT, TAP, deductible VAT, and IRG templates directly from the program.",
    f4Title: "Opening balances",
    f4Text: "Import and use opening balances with management adapted to accounts and third parties.",
    f5Title: "Potential anomalies",
    f5Text: "Spot transactions that require verification without automatically concluding that they are errors.",
    f6Title: "Built-in updates",
    f6Text: "Evolve the application through an integrated manual update system.",
    interfaceKicker: "Interface",
    interfaceTitle: "A clear interface to read your data better.",
    interfaceText1: "Comptivo’s interface highlights what matters most: indicators, reports, searches, and items that deserve your attention.",
    interfaceText2: "The preview shown here is a promotional illustration based on a software screenshot with fictional data.",
    b1: "Simple and organized navigation.",
    b2: "Fast reading of important indicators.",
    b3: "A concise view of key information.",
    b4: "Presentation adapted for professional use.",
    audienceKicker: "Who is it for?",
    audienceTitle: "A solution intended for accounting professionals and organizations.",
    a1Title: "Accountants",
    a1Text: "To speed up checks and quickly find useful information.",
    a2Title: "Accounting firms",
    a2Text: "To centralize analysis and improve file follow-up.",
    a3Title: "Companies",
    a3Text: "To gain a clearer view of accounting and items that need verification.",
    ctaKicker: "Why Comptivo?",
    ctaTitle: "Simpler. Faster. More structured.",
    ctaText: "Comptivo helps you save time in your accounting reviews, searches, and checks while keeping the user at the center of the decision.",
    ctaButton: "Request information",
    contactKicker: "Contact",
    contactTitle: "Let’s talk about your needs with Comptivo.",
    contactIntro: "For a software presentation, more information, or a professional inquiry, you can contact us using the channels below.",
    contactEmailTitle: "Email",
    contactFacebookTitle: "Facebook",
    contactFacebookText: "Official Comptivo page",
    panelTitle: "Comptivo",
    panelText: "Accounting analysis and control software designed to provide a clearer and more efficient reading of your data.",
    panelEmailButton: "Send an email",
    panelFacebookButton: "Visit Facebook",
    footerText: "Comptivo — multilingual promotional presentation."
  },
  ar: {
    navAbout: "حول البرنامج",
    navFeatures: "المزايا",
    navInterface: "الواجهة",
    navContact: "التواصل",
    heroBadge: "Comptivo V1.03 • ويندوز 10/11",
    heroTitle: "تحليل محاسبي أوضح وأسرع وأكثر تنظيماً.",
    heroText: "يجمع Comptivo عمليات المراقبة والبحث والعروض المحاسبية داخل واجهة حديثة صُممت لتوفير الوقت ومساعدتك على استغلال بياناتك بشكل أفضل.",
    heroPrimary: "اكتشف البرنامج",
    heroSecondary: "تواصل معنا",
    point1Title: "تحليل محاسبي",
    point1Text: "بحث ومراقبة وقراءة أفضل للبيانات",
    point2Title: "تقارير ومؤشرات",
    point2Text: "رؤية مركزية للنشاط",
    point3Title: "بيانات محلية",
    point3Text: "محفوظة على جهاز العمل",
    demoLabel: "معاينة للواجهة — بيانات وهمية",
    strip1: "بحث شامل",
    strip2: "تقارير محاسبية",
    strip3: "ملفات جبائية",
    strip4: "الأرصدة السابقة",
    strip5: "كشف الشذوذ",
    aboutKicker: "حول البرنامج",
    aboutTitle: "حل صُمم لتبسيط التحليل المحاسبي.",
    aboutP1: "Comptivo هو برنامج مخصص للتحليل والمراقبة المحاسبية. يساعد المهنيين على الوصول إلى المعلومات بسرعة أكبر، وعرض مؤشرات مفيدة، وتنظيم عمليات التحقق داخل بيئة واحدة.",
    aboutP2: "يرافق البرنامج المستخدم في عمليات المراجعة دون أن يعوض الحكم المهني. يجب فهم التنبيهات على أنها نقاط تستحق التحقق، وليست أخطاء مؤكدة بشكل آلي.",
    featuresKicker: "المزايا",
    featuresTitle: "الأدوات الأساسية مجتمعة داخل تطبيق واحد.",
    featuresIntro: "يقدم Comptivo واجهة واضحة للعمل بكفاءة أكبر على بياناتك المحاسبية.",
    f1Title: "بحث شامل",
    f1Text: "اعثر بسرعة على حساب أو طرف أو رقم وثيقة أو مرجع أو يومية أو بيان أو مبلغ.",
    f2Title: "لوحة قيادة",
    f2Text: "تابع المؤشرات الأساسية والأرقام الملخصة والمعلومات المفيدة داخل نظرة عامة حديثة.",
    f3Title: "ملفات جبائية",
    f3Text: "العمل على نماذج TVA وTAP وTVA à déduire وIRG مباشرة من البرنامج.",
    f4Title: "الأرصدة السابقة",
    f4Text: "استيراد واستغلال الأرصدة السابقة مع معالجة مناسبة للحسابات والأطراف.",
    f5Title: "شذوذات محتملة",
    f5Text: "اكتشف العمليات التي تتطلب تحققاً دون الجزم تلقائياً بأنها أخطاء.",
    f6Title: "تحديث مدمج",
    f6Text: "طوّر التطبيق عبر نظام تحديث يدوي مدمج.",
    interfaceKicker: "الواجهة",
    interfaceTitle: "واجهة واضحة لقراءة أفضل لبياناتك.",
    interfaceText1: "تُبرز واجهة Comptivo ما هو مهم: المؤشرات والتقارير وعمليات البحث والعناصر التي تستحق انتباهك.",
    interfaceText2: "المعاينة المعروضة هنا هي صورة ترويجية مبنية على لقطة من البرنامج مع بيانات وهمية.",
    b1: "تنقل بسيط ومنظم.",
    b2: "قراءة سريعة للمؤشرات المهمة.",
    b3: "رؤية مختصرة للمعلومات الأساسية.",
    b4: "عرض مناسب للاستعمال المهني.",
    audienceKicker: "لمن هذا البرنامج؟",
    audienceTitle: "حل موجه للمهنيين والهياكل المحاسبية.",
    a1Title: "المحاسبون",
    a1Text: "لتسريع المراجعات والوصول بسرعة إلى المعلومات المهمة.",
    a2Title: "مكاتب المحاسبة",
    a2Text: "لتجميع التحليل وتحسين متابعة الملفات.",
    a3Title: "الشركات",
    a3Text: "للحصول على قراءة أوضح للمحاسبة والنقاط التي تحتاج إلى تحقق.",
    ctaKicker: "لماذا Comptivo؟",
    ctaTitle: "أبسط. أسرع. أكثر تنظيماً.",
    ctaText: "يساعدك Comptivo على ربح الوقت في القراءة والبحث والمراجعة المحاسبية مع إبقاء المستخدم في صلب القرار.",
    ctaButton: "اطلب معلومات",
    contactKicker: "التواصل",
    contactTitle: "لنتحدث عن احتياجك مع Comptivo.",
    contactIntro: "للحصول على عرض للبرنامج أو مزيد من المعلومات أو للتواصل المهني، يمكنك مراسلتنا عبر الوسائل التالية.",
    contactEmailTitle: "البريد الإلكتروني",
    contactFacebookTitle: "فيسبوك",
    contactFacebookText: "الصفحة الرسمية لـ Comptivo",
    panelTitle: "Comptivo",
    panelText: "برنامج للتحليل والمراقبة المحاسبية صُمم لتقديم قراءة أوضح وأكثر فعالية لبياناتك.",
    panelEmailButton: "إرسال بريد",
    panelFacebookButton: "زيارة فيسبوك",
    footerText: "Comptivo — صفحة ترويجية متعددة اللغات."
  }
};

function setLanguage(lang){
  const dict = translations[lang] || translations.fr;
  document.documentElement.lang = lang === 'ar' ? 'ar' : lang;
  document.body.dir = lang === 'ar' ? 'rtl' : 'ltr';

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if(dict[key]) el.textContent = dict[key];
  });

  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  localStorage.setItem('comptivo_lang', lang);
}

const savedLang = localStorage.getItem('comptivo_lang') || 'fr';
setLanguage(savedLang);

document.querySelectorAll('.lang-btn').forEach(btn => {
  btn.addEventListener('click', () => setLanguage(btn.dataset.lang));
});

const menuToggle = document.getElementById('menuToggle');
const mainNav = document.getElementById('mainNav');
menuToggle?.addEventListener('click', () => {
  mainNav.classList.toggle('open');
});

document.querySelectorAll('.main-nav a').forEach(link => {
  link.addEventListener('click', () => mainNav.classList.remove('open'));
});
